---
- name: Add an OpenStack project <{{ os_service_name }}>
  vars:
    state_file: '{{ state_files_dir }}/add_project.sh.state'
  script: |
    ../../scripts/add_project.sh '{{ state_file }}' '{{ os_env_file }}' '{{ os_service_name }}' '{{ os_domain_name }}' '{{ os_service_desc }}'
  args:
    creates: '{{ state_file }}'
  register: exec_result


