---
- name: Installing required packages
  apt: name=rabbitmq-server state=latest


- name: Adding an OpenStack user
  rabbitmq_user:
    user: "{{ rabbitmq_username }}"
    password: "{{ rabbitmq_password }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

