---


- name: Placing udev rules for proper naming network interfaces
  lineinfile: 
    dest: "/etc/udev/rules.d/70-persistent-net.rules"
    line: 'SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="{{ item.hwaddr }}", NAME="{{ item.ifname }}"'
    owner: root
    group: root
    mode: 0644
    state: present
    create: yes
  register: reboot_required
  with_items: "{{ system_network_interfaces }}"


- name: Set new hostname (if specified)
  hostname: name="{{ hostname_new }}"
  when: hostname_new is defined


- name: Remove cloud-init (very slow) package
  apt: name=cloud-init state=absent


- name: Reboot the server if necessary
  shell: nohup bash -c "sleep 2s && reboot" &
  async: 0
  poll: 0
  when: reboot_required.changed == True
  ignore_errors: true


- name: Wait for the server comes back
  local_action: wait_for host={{ ansible_ssh_host }} state=started delay=10 timeout=60 connect_timeout=300
  when: reboot_required.changed == True


- name: Put network interfaces file
  template:
    src: interfaces.j2
    dest: "{{ interfaces_rootdir }}/interfaces"
    owner: root
    group: root
    mode: 0644


#- name: Create interfaces config files
#  template:
#    src: inteface.cfg.j2
#    dest: "{{ interfaces_configs }}/{{ item.ifname }}.cfg"
#  with_items: "{{ system_network_interfaces }}"
#  when: "{{ item.role }} in {{ interfaces_roles_linux }}"


