---
- name: Configure Neutron agents and services
  template:
    src: '{{ item.src }}.j2'
    dest: '/etc/neutron/{{ item.dest }}'
    owner: neutron
    group: neutron
    mode: 0640
  with_items:
  - { src: dhcp_agent.ini, dest: dhcp_agent.ini }
  - { src: neutron.conf, dest: neutron.conf }
  - { src: ml2_conf.ini, dest: plugins/ml2/ml2_conf.ini }
  - { src: linuxbridge_agent.ini, dest: plugins/ml2/linuxbridge_agent.ini }
  - { src: metadata_agent.ini, dest: metadata_agent.ini }
  notify:
  - restart_neutron


- name: Run required services
  service: name='{{ item }}' state=started enabled=on
  with_items: '{{ neutron_services }}'


- name: Populate Neutron database
  shell: 'su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron'


