neutron_packages:
- neutron-server
- neutron-plugin-ml2
- neutron-linuxbridge-agent
- neutron-dhcp-agent
- neutron-metadata-agent

neutron_services: 
- neutron-server
- neutron-linuxbridge-agent
- neutron-dhcp-agent
- neutron-metadata-agent
#- neutron-l3-agent

